### ISSUE TITLE
terrafor az in windows  not working  - Error: json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by Veljen** [XtratusCloud/terraform-provider-azureipam#10]
I tried with linux machine and it works fine as expected. same code in windows (using az cli/terraform) its not working and gives the below error.

Az cli  version 2.56.0
Terraform CLI version 1.6.0
OS :  Windows 11

```



Planning failed. Terraform encountered an error while generating this plan.
 
╷

│ Error: Unexpected External Program Results

│

│   with data.external.get_access_token,

│   on providers.tf line 20, in data "external" "get_access_token":

│   20:   program = ["az", "account", "get-access-token", "--resource", "api://${local.ipam_apiId}"]

│

│ The data source received unexpected results after executing the program.

│

│ Program output must be a JSON encoded map of string keys and string values.

│

│ If the error is unclear, the output can be viewed by enabling Terraform's

│ logging at TRACE level. Terraform documentation on logging:

│ https://www.terraform.io/internals/debugging

│

│ Program: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd

│ Result Error: json: cannot unmarshal number into Go value of type string
Debugging | Terraform | HashiCorp Developer
Terraform has detailed logs which can be enabled by setting the TF_LOG environment variable to any value. This will cause detailed logs to appear on stderr
```

**Comment by XtratusCloud** [comment]
Hi @Veljen ,
We have already detected this problem in some of my implementations and it is due to the fact that the latest versions of az cli return additional information related to the access-token that is not directly serializable to JSON.

You can modify the az cli command to return only the required value, the access-token, as show below,
![image](https://github.com/XtratusCloud/terraform-provider-azureipam/assets/122672536/34e07f01-512f-46ff-b5f2-19818c2938e1)

and then you must also modify slightly the terraform code that uses it
![image](https://github.com/XtratusCloud/terraform-provider-azureipam/assets/122672536/e74f3180-2e8a-4c25-8683-b8b5a298debc)

I hope it has been helpfu
