### ISSUE TITLE
Help | Terraform cloud

### ISSUE THREAD

**Issue by grabskimm** [XtratusCloud/terraform-provider-azureipam#9]
Can this provider be used while running it on Terraform cloud agent (default)? 

I have been testing around with this, and while it runs great locally, it fails to run properly on terraform cloud agent since `az` program is not installed on terraform cloud agent hardware.

Any known easy workarounds? 

```
Error:`` External Program Lookup Failed
with data.external.get_access_token
on locals.tf line 8, in data "external" "get_access_token":
  program = ["az", "account", "get-access-token", "--resource", "api://${local.ipam_apiId}"]
The data source received an unexpected error while attempting to parse the query. The data source received an unexpected error while attempting to find the program.

The program must be accessible according to the platform where Terraform is running.

If the expected program should be automatically found on the platform where Terraform is running, ensure that the program is in an expected directory. On Unix-based platforms, these directories are typically searched based on the '$PATH' environment variable. On Windows-based platforms, these directories are typically searched based on the '%PATH%' environment variable.

If the expected program is relative to the Terraform configuration, it is recommended that the program name includes the interpolated value of 'path.module' before the program name to ensure that it is compatible with varying module usage. For example: "${path.module}/my-program"

The program must also be executable according to the platform where Terraform is running. On Unix-based platforms, the file on the filesystem must have the executable bit set. On Windows-based platforms, no action is typically necessary.

Platform: linux
Program: "az"
Error: exec: "az": executable file not found in $PATH
```

**Comment by XtratusCloud** [comment]
Hi @grabskimm ,
The "AZ CLI" task included in the examples is used to obtain the access token needed to invoke the IPAM API.
This token can also be specified usin tne AZUREIPAM_TOKEN environment variable, as is specified in the provider documentation, as a temporarily workaround to test the provider.
You can obtain the token in an earlier step of your pipeline and assign it as an environment variable.

For a productive environment it would be recommended to use Terraform Cloud Agents, since with the standard agents it would be necessary to publish the IPAM API to publicly access, and you will not be able to control the additional software needed for your terraform deployments.

**Comment by grabskimm** [comment]
Hi @XtratusCloud  - Thank you for clarifying.  

The latest issue I am facing is when terraform is refreshing state and the token has already expired the plan will fail, during plan time Terraform has not generated a new token yet for access. Any way to bypass during plan refresh?

The error is very generic as follows

```
azureipam_reservation.ipam_reservation: Refreshing state... [id=4hTzh95ZYSMU6r3FCAgVap]
╷
│ Error: Get "/api/spaces/azure/blocks/mgmt-wus2/reservations?settled=true": unsupported protocol scheme ""
│
│   with azureipam_reservation.ipam_reservation,
│   on main.tf line 2, in resource "azureipam_reservation" "ipam_reservation":
│    2: resource "azureipam_reservation" "ipam_reservation" {
```
